# Generated by Django 2.0.2 on 2018-07-16 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 16, 13, 11, 7, 581837))),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
