# Generated by Django 2.0.2 on 2018-07-16 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 16, 14, 10, 40, 13631))),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
