# Generated by Django 2.0.2 on 2018-07-16 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180716_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 16, 14, 40, 13, 952626)),
        ),
    ]
