# Generated by Django 2.0.2 on 2018-07-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180704_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateField(),
        ),
    ]
